//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesYes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public string boleta { get; set; }
        public string nombre { get; set; }
        public string CURP { get; set; }
        public string fechaNac { get; set; }
    }
}
