//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesYes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universidad
    {
        public int IDuniversidad { get; set; }
        public string Nombre { get; set; }
    }
}
